"use client";

import { useRef, useState } from "react";
import Image from "next/image";
import { track } from "@vercel/analytics";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { motion, useReducedMotion } from "motion/react";
import { ArrowRight, Blocks, Bot, Camera, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clapperboard, Code2, Gauge, Globe2, Layers3, LayoutDashboard, Menu, MessageCircle, MonitorSmartphone, Palette, Play, Quote, Rocket, Send, ShieldCheck, ShoppingBag, Sparkles, Star, Users, WandSparkles, X, Zap } from "lucide-react";
import { faqs, packages, projects, services, testimonials } from "./data";

export const WHATSAPP_NUMBER = "15513090145";
const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("Hola, quiero solicitar información sobre un proyecto con LoEditamos.")}`;

const quoteSchema = z.object({ name: z.string().min(2, "Escribe tu nombre"), project: z.string().min(1, "Selecciona una opción"), date: z.string(), description: z.string().min(20, "Cuéntanos un poco más (mínimo 20 caracteres)") });
type QuoteData = z.infer<typeof quoteSchema>;

const nav = [["Desarrollo web", "#desarrollo"], ["Edición de video", "#video"], ["Proyectos", "#proyectos"], ["Cómo trabajamos", "#proceso"], ["Preguntas frecuentes", "#faq"]];

function CTAButton({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) {
  return <a href={href} className={`btn ${secondary ? "btn-secondary" : "btn-primary"}`}>{children}<ArrowRight size={17} aria-hidden /></a>;
}
function SectionHeading({ eyebrow, title, text, light = false }: { eyebrow?: string; title: React.ReactNode; text?: string; light?: boolean }) {
  return <div className={`section-heading ${light ? "light" : ""}`}>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{text && <p>{text}</p>}</div>;
}
function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-70px" }} transition={{ duration: .55, ease: "easeOut" }}>{children}</motion.div>;
}

function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="container header-inner"><a className="logo" href="#inicio" aria-label="LoEditamos, inicio">LoEditamos<span>.</span></a><nav className="desktop-nav" aria-label="Navegación principal">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div className="header-actions"><a className="header-quote" href="#cotizacion">Solicitar cotización</a><button className="menu-btn" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open ? "Cerrar menú" : "Abrir menú"}>{open ? <X /> : <Menu />}</button></div></div>{open && <nav id="mobile-menu" className="mobile-nav" aria-label="Navegación móvil">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}<a className="btn btn-primary" href="#cotizacion" onClick={() => setOpen(false)}>Solicitar cotización</a></nav>}</header>;
}

function HeroVisual() {
  return <div className="hero-visual" aria-label="Vista conceptual de una web, una aplicación y edición de video" role="img"><div className="orb" /><div className="laptop"><div className="laptop-screen"><div className="screen-nav"><b>LO.</b><i /><i /><i /></div><div className="screen-copy"><small>EXPERIENCIAS DIGITALES</small><strong>Diseño que impulsa<br />tu próxima idea.</strong><span>Soluciones creadas para crecer contigo.</span><button>Explorar</button></div><div className="screen-panels"><i /><i /><i /></div></div><div className="laptop-base" /></div><div className="phone"><div className="phone-notch" /><small>Mi negocio</small><b>Resumen</b><div className="phone-card">Ventas <strong>+24%</strong></div><svg viewBox="0 0 180 60" aria-hidden><path d="M0 48 C25 44 28 12 55 25 S95 54 115 29 S148 13 180 5" fill="none" stroke="#7c3aed" strokeWidth="5" /></svg><div className="phone-dots"><i /><i /><i /></div></div><div className="editor"><div className="preview"><Play size={22} fill="white" /></div><div className="timeline"><i /><i /><i /></div></div><div className="float-card card-one"><Palette size={18} /> Diseño a medida</div><div className="float-card card-two"><Bot size={18} /> Aplicaciones Android</div><div className="float-card card-three"><Clapperboard size={18} /> Edición profesional</div><div className="float-card card-four"><MonitorSmartphone size={18} /> 100% responsive</div></div>;
}

function Hero() { return <section className="hero" id="inicio"><div className="hero-grid container"><Reveal className="hero-copy"><p className="eyebrow">DISEÑO WEB · APPS · EDICIÓN DE VIDEO</p><h1>Creamos la solución digital que <span>tu negocio necesita.</span></h1><p className="hero-text">Diseñamos páginas web, plataformas y aplicaciones a medida. También editamos contenido audiovisual que conecta con tu audiencia y ayuda a crecer tu marca.</p><div className="hero-proof"><span className="proof-avatars"><i>PA</i><i>MX</i><i>CO</i></span><span><b>Más de 50 proyectos</b><small>desarrollados a nivel mundial</small></span></div><div className="button-row"><CTAButton href="#cotizacion">Cuéntanos tu proyecto</CTAButton><CTAButton href="#servicios" secondary>Ver nuestros servicios</CTAButton></div><div className="hero-note"><Sparkles size={19} /><p><b>No necesitas tenerlo todo definido.</b><br />Te ayudamos a organizar tu idea y convertirla en un proyecto claro.</p></div></Reveal><Reveal><HeroVisual /></Reveal></div></section>; }

const trust = [[WandSparkles, "Proyectos personalizados", "Cada negocio es único."], [Users, "Acompañamiento total", "De la idea al lanzamiento."], [MessageCircle, "Comunicación directa", "Hablamos claro y simple."], [Blocks, "Soluciones escalables", "Crecemos contigo."]];
function TrustBar() { return <section className="trust-bar" aria-label="Nuestros compromisos"><div className="container trust-grid">{trust.map(([Icon, title, text]) => { const I = Icon as typeof Sparkles; return <div className="trust-item" key={String(title)}><span><I size={22} /></span><div><b>{String(title)}</b><p>{String(text)}</p></div></div>; })}</div></section>; }

function ServiceCard({ variant, title, description, items, cta }: { variant: "purple" | "blue"; title: string; description: string; items: string[]; cta: string }) { const Icon = variant === "purple" ? Code2 : Clapperboard; return <article className={`service-card ${variant}`}><div className="service-title"><span><Icon /></span><div><h3>{title}</h3><p>{description}</p></div></div><ul>{items.map(item => <li key={item}><CheckCircle2 size={16} />{item}</li>)}</ul><CTAButton href="#cotizacion">{cta}</CTAButton></article>; }
function Services() { return <section className="section" id="servicios"><div className="container"><SectionHeading eyebrow="NUESTROS SERVICIOS PRINCIPALES" title={<>Dos pilares, una misma misión: <span>hacerte crecer.</span></>} /><Reveal className="services-grid"><ServiceCard variant="purple" title="Desarrollo web y aplicaciones" description="Creamos sitios web, plataformas y aplicaciones adaptadas a tu negocio, tus clientes y tus objetivos." items={services.web} cta="Cotizar mi proyecto" /><ServiceCard variant="blue" title="Edición de video" description="Convertimos tus ideas y grabaciones en contenido profesional listo para publicar." items={services.video} cta="Ver opciones de edición" /></Reveal></div></section>; }

const packageIcons = { landing: Rocket, web: Globe2, app: MonitorSmartphone, video: Clapperboard };
function Packages(){return <section className="packages-section"><div className="container"><SectionHeading eyebrow="FORMAS DE EMPEZAR" title={<>Una solución para <span>cada etapa de tu negocio.</span></>} text="Estas modalidades son una guía inicial. El alcance final se adapta a tus objetivos, tiempos y necesidades."/><div className="packages-grid">{packages.map(item=>{const Icon=packageIcons[item.icon as keyof typeof packageIcons];return <article className={`package-card ${item.featured?"featured":""}`} key={item.name}>{item.featured&&<span className="popular">MÁS SOLICITADO</span>}<span className="package-icon"><Icon/></span><p className="eyebrow">{item.eyebrow}</p><h3>{item.name}</h3><p>{item.description}</p><ul>{item.features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul><a href={item.href} onClick={()=>track("Proyecto consultado",{tipo:"paquete",proyecto:item.name})}>Conocer el servicio <ArrowRight size={16}/></a></article>})}</div></div></section>}

const webTypes = [[Globe2,"Sitios corporativos","Presenta tu empresa con claridad y credibilidad."],[Rocket,"Landing pages","Campañas enfocadas en una acción concreta."],[ShoppingBag,"Tiendas en línea","Vende de forma simple, segura y disponible 24/7."],[Layers3,"Plataformas personalizadas","Herramientas digitales ajustadas a tu operación."],[LayoutDashboard,"Sistemas administrativos","Organiza datos, clientes y procesos internos."],[Bot,"Aplicaciones Android","Lleva tu servicio a las manos de tus clientes."]];
function WebDevelopment() { return <section className="section web-section" id="desarrollo"><div className="container"><SectionHeading eyebrow="DESARROLLO A TU MEDIDA" title={<>No hacemos páginas genéricas. <span>Creamos herramientas para tu negocio.</span></>} text="Tu página web puede ayudarte a generar prospectos, presentar tus servicios, vender productos, automatizar procesos y transmitir confianza." /><div className="web-grid">{webTypes.map(([Icon,t,d]) => { const I=Icon as typeof Globe2; return <Reveal key={String(t)} className="web-item"><I /><h3>{String(t)}</h3><p>{String(d)}</p></Reveal>})}</div></div></section>; }

const benefits=[[ShieldCheck,"Genera confianza","Una presencia profesional transmite seguridad y credibilidad."],[Layers3,"Organiza tu oferta","Tus clientes entienden qué haces y cómo contactarte."],[Zap,"Convierte visitas","Diseñamos para que tus visitantes actúen."],[Rocket,"Te permite crecer","Escala con funcionalidades, ventas y automatizaciones."]];
function WebsiteBenefits(){return <section className="benefits-wrap"><div className="container benefits"><div className="benefits-lead"><p className="eyebrow">¿POR QUÉ TENER UNA WEB PROFESIONAL?</p><h2>Tu página web <span>trabaja</span> incluso cuando tú <span>no estás.</span></h2></div>{benefits.map(([Icon,t,d])=>{const I=Icon as typeof Rocket;return <div className="benefit" key={String(t)}><I/><h3>{String(t)}</h3><p>{String(d)}</p></div>})}</div></section>}

const steps=[[MessageCircle,"Cuéntanos qué necesitas","Escríbenos por WhatsApp o completa el formulario."],[Users,"Entendemos tu proyecto","Revisamos tus objetivos, público y prioridades."],[CircleDollarSign,"Preparamos la propuesta","Recibes alcance, tiempos y costos con claridad."],[Code2,"Diseñamos y desarrollamos","Trabajamos por etapas y te mantenemos al tanto."],[CheckCircle2,"Revisamos y publicamos","Probamos, ajustamos y dejamos todo listo."]];
function Process(){return <section className="section" id="proceso"><div className="container"><SectionHeading eyebrow="CÓMO TRABAJAMOS" title={<>Un proceso <span>simple y claro.</span></>}/><div className="process-grid">{steps.map(([Icon,t,d],i)=>{const I=Icon as typeof Users;return <Reveal className="process-step" key={String(t)}><span className="step-number">{i+1}</span><I/><h3>{String(t)}</h3><p>{String(d)}</p></Reveal>})}</div><p className="process-note">¿Todavía no sabes exactamente qué necesitas? <b>Nosotros te ayudamos a definirlo.</b></p></div></section>}

function VideoEditing(){const features=["Cortes y limpieza","Música","Subtítulos","Transiciones","Corrección de color","Efectos de sonido","Motion graphics","Inserción de logotipo","Formatos vertical, horizontal y cuadrado"];return <section className="video-section" id="video"><div className="container video-grid"><Reveal><SectionHeading light eyebrow="EDICIÓN PROFESIONAL" title={<>Tú creas. <span>Nosotros lo convertimos</span> en contenido listo para publicar.</>} text="Editamos videos para empresas, emprendimientos, negocios locales y creadores. Trabajamos por proyecto, por paquete o con una edición recurrente adaptada a tu ritmo."/><div className="video-plans"><span>Edición por proyecto</span><span>Paquetes de contenido</span><span>Edición recurrente</span></div><ul className="video-features">{features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><CTAButton href="#cotizacion">Cuéntanos qué videos necesitas</CTAButton></Reveal><Reveal className="video-editor"><div className="editor-top"><i/><i/><i/><b>Proyecto_01</b></div><div className="editor-preview"><div className="preview-person"><span>Tu historia,<br/><b>mejor contada.</b></span><Play fill="white"/></div></div><div className="editor-tools"><span/><span/><span/><span/><span/></div><div className="editor-tracks"><b>00:12:08</b><i className="track-purple"/><i className="track-blue"/><i className="track-audio"/><em/></div></Reveal></div></section>}

function Portfolio(){const [filter,setFilter]=useState("Todos");const filters=["Todos","Sitios web","Aplicaciones"];const shown=filter==="Todos"?projects:projects.filter(p=>p.type===filter);return <section className="section portfolio-section" id="proyectos"><div className="container"><SectionHeading eyebrow="ALGUNOS DE NUESTROS CLIENTES" title={<>Proyectos reales, diseñados para <span>marcas con objetivos distintos.</span></>} text="Cada solución responde a una identidad, una audiencia y una necesidad concreta."/><div className="filters" role="group" aria-label="Filtrar proyectos">{filters.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)} aria-pressed={filter===f}>{f}</button>)}</div><div className="portfolio-grid real-projects">{shown.map((p,index)=><article className={`project-card real-project device-${p.device}`} key={p.name}><div className={`project-showcase ${p.accent}`}>{p.device==="desktop"?<div className="desktop-mockup"><div className="desktop-camera"/><div className="desktop-screen"><Image src={p.image} alt={`Proyecto de ${p.name}`} fill sizes="(max-width: 768px) 100vw, 50vw" priority={index===0}/></div><div className="desktop-stand"><i/></div></div>:<div className="phone-mockup"><div className="phone-speaker"/><div className="phone-project-screen"><Image src={p.image} alt={`Aplicación ${p.name}`} fill sizes="(max-width: 768px) 70vw, 25vw"/></div><div className="phone-home"/></div>}<span className="project-number">0{index+1}</span></div><div className="project-copy"><small>{p.type}</small><h3>{p.name}</h3><p>{p.desc}</p><div>{p.tags.map(t=><span key={t}>{t}</span>)}<a href="#cotizacion" aria-label={`Consultar por un proyecto como ${p.name}`} onClick={()=>track("Proyecto consultado",{tipo:p.type,proyecto:p.name})}><ArrowRight size={17}/></a></div></div></article>)}</div></div></section>}

function Testimonials(){return <section className="testimonials-section"><div className="container"><SectionHeading eyebrow="EXPERIENCIAS" title={<>Proyectos que se sienten <span>cercanos, incluso a distancia.</span></>} text="Acompañamos ideas de distintos países con la misma comunicación clara y atención al detalle."/><div className="testimonials-grid">{testimonials.map(item=><article className="testimonial-card" key={item.name}><div className="testimonial-top"><span className="quote-icon"><Quote/></span><span className="stars" aria-label="5 de 5 estrellas">{Array.from({length:5}).map((_,i)=><Star key={i} fill="currentColor"/>)}</span></div><blockquote>“{item.quote}”</blockquote><div className="testimonial-person"><span className="person-avatar">{item.name.split(" ").map(x=>x[0]).join("")}</span><div><b>{item.name}</b><small>{item.role}</small></div><span className="country"><Image src={`https://flagcdn.com/${item.countryCode}.svg`} alt={`Bandera de ${item.country}`} width={24} height={18} unoptimized/>{item.country}</span></div></article>)}</div></div></section>}

const reasons=[[WandSparkles,"Soluciones personalizadas"],[Users,"Ayuda para definir tu proyecto"],[MessageCircle,"Comunicación clara"],[Palette,"Diseño moderno"],[Gauge,"Desarrollo escalable"],[Clapperboard,"Web y video en un equipo"]];
function WhyChooseUs(){return <section className="why"><div className="container why-grid"><SectionHeading eyebrow="POR QUÉ LOEDITAMOS" title={<>Un equipo flexible para proyectos que <span>no caben en una plantilla.</span></>} text="Combinamos estrategia, diseño y ejecución para construir justo lo que tu negocio necesita hoy, sin limitar lo que podrá ser mañana."/><div className="reason-grid">{reasons.map(([Icon,t])=>{const I=Icon as typeof Users;return <div key={String(t)}><I/><span>{String(t)}</span></div>})}</div></div></section>}

function FAQ(){return <section className="section faq" id="faq"><div className="container faq-grid"><SectionHeading eyebrow="PREGUNTAS FRECUENTES" title={<>Respuestas claras <span>antes de empezar.</span></>} text="Si tu pregunta no está aquí, escríbenos. Una conversación breve suele ser suficiente para orientarte."/><div className="accordion">{faqs.map((faq,i)=><details key={faq.q} open={i===0}><summary>{faq.q}<ChevronDown size={20}/></summary><p>{faq.a}</p></details>)}</div></div></section>}

function QuoteForm(){const started=useRef(false);const {register,handleSubmit,formState:{errors}}=useForm<QuoteData>({resolver:zodResolver(quoteSchema),defaultValues:{date:""}});function startForm(){if(!started.current){started.current=true;track("Inicio del formulario",{formulario:"cotizacion"})}}function submit(data:QuoteData){track("Cotizacion enviada",{tipo:data.project,fecha_definida:Boolean(data.date)});const message=["Hola, quiero solicitar una cotización con LoEditamos.","",`Nombre: ${data.name}`,`Tipo de proyecto: ${data.project}`,`Fecha estimada: ${data.date||"Por definir"}`,"",`Descripción: ${data.description}`].join("\n");window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}return <section className="quote-section" id="cotizacion"><div className="container quote-grid"><div><p className="eyebrow">HABLEMOS DE TU PROYECTO</p><h2>Cuéntanos qué quieres crear.</h2><p>Solo necesitamos cuatro datos. Tu solicitud se abrirá directamente en WhatsApp para que puedas revisarla antes de enviarla.</p><a className="quote-whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer" onClick={()=>track("Clic en WhatsApp",{ubicacion:"formulario_directo"})}><span><MessageCircle/></span><div><b>¿Prefieres escribir directamente?</b><small>+1 (551) 309-0145</small></div><ArrowRight/></a></div><form onSubmit={handleSubmit(submit)} onFocus={startForm} noValidate><div className="form-grid"><Field label="Nombre *" error={errors.name?.message} wide><input {...register("name")} autoComplete="name"/></Field><Field label="Tipo de proyecto *" error={errors.project?.message}><select {...register("project")} defaultValue=""><option value="" disabled>Selecciona una opción</option>{["Página web","Landing page","Tienda en línea","Plataforma","Aplicación Android","Página web más aplicación","Edición de video","No estoy seguro"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fecha estimada"><input type="date" {...register("date")}/></Field><Field label="Descripción del proyecto *" error={errors.description?.message} wide><textarea rows={5} {...register("description")} placeholder="¿Qué quieres crear y qué objetivo buscas?"/></Field></div><button className="btn btn-primary submit-btn">Cotizar por WhatsApp<Send size={17}/></button></form></div></section>}
function Field({label,error,children,wide=false}:{label:string;error?:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}

function FinalCTA(){return <section className="container final-cta"><div><h2>Tu idea puede empezar con una simple conversación.</h2><p>Cuéntanos qué quieres crear. Si todavía no tienes todos los detalles, te ayudaremos a encontrar el mejor camino.</p></div><div className="button-row"><a className="btn cta-whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer" onClick={()=>track("Clic en WhatsApp",{ubicacion:"cta_final"})}><MessageCircle/>Hablar por WhatsApp</a><a className="btn cta-light" href="#cotizacion">Solicitar cotización<ArrowRight/></a></div></section>}
function Footer(){return <footer><div className="container footer-grid"><div><a className="logo footer-logo" href="#inicio">LoEditamos<span>.</span></a><p>Diseñamos, desarrollamos y editamos soluciones digitales que impulsan negocios y marcas.</p><div className="socials"><a href="https://instagram.com/loeditamos" target="_blank" rel="noreferrer" aria-label="Instagram de LoEditamos"><Camera/></a><a href="https://instagram.com/loeditamos" target="_blank" rel="noreferrer">@loeditamos</a></div></div><div><h3>Servicios</h3><a href="#desarrollo">Desarrollo web</a><a href="#desarrollo">Aplicaciones Android</a><a href="#video">Edición de video</a><a href="#video">Edición de Reels</a></div><div><h3>Enlaces</h3><a href="#proceso">Cómo trabajamos</a><a href="#proyectos">Proyectos</a><a href="#faq">Preguntas frecuentes</a><a href="#cotizacion">Contacto</a></div><div><h3>Contacto</h3><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" onClick={()=>track("Clic en WhatsApp",{ubicacion:"footer"})}>+1 (551) 309-0145</a><p>Lunes a viernes<br/>9:00 a.m. – 6:00 p.m.</p></div><div><h3>Ideas útiles, sin spam.</h3><p>Recibe tips para hacer crecer tu negocio.</p><form className="subscribe" onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="subscribe-email">Tu correo electrónico</label><input id="subscribe-email" type="email" placeholder="Tu correo electrónico" required/><button aria-label="Suscribirme"><ArrowRight/></button></form></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} LoEditamos. Todos los derechos reservados.</span><div><a href="/privacidad">Privacidad</a><a href="/terminos">Términos</a><a href="/cookies">Cookies</a></div></div></footer>}

export function LandingPage(){return <><Header/><main><Hero/><TrustBar/><Services/><Packages/><WebDevelopment/><WebsiteBenefits/><Process/><VideoEditing/><Portfolio/><Testimonials/><WhyChooseUs/><FAQ/><QuoteForm/><FinalCTA/></main><Footer/><a className="floating-whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer" aria-label="Hablar por WhatsApp" onClick={()=>track("Clic en WhatsApp",{ubicacion:"boton_flotante"})}><MessageCircle/></a></>}
